package crudbuild

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/bufbuild/protocompile"
	"github.com/nxnminieye/nexa/generation/entity"
	genprotocol "github.com/nxnminieye/nexa/generation/protocol"
	"github.com/nxnminieye/nexa/provenance"
)

const (
	GeneratedProtoMarker = "// Code generated by nexactl generation crud write. DO NOT EDIT."
	MaxSchemaKeyBytes    = 235
)

// FragmentSpec contains only the fact inputs needed to build CRUD protocol fragments.
type FragmentSpec struct {
	ServiceID    string
	ProtoPackage string
	GoPackage    string
	ExistingLock *Lock
	MultiTenant  MultiTenantConfig
}

type FragmentProjection struct{ state *fragmentProjectionState }
type ProtoFragment struct{ state *protoFragmentState }
type SchemaID string
type SchemaKey string

type fragmentProjectionState struct {
	fragments      []*protoFragmentState
	entitySnapshot []byte
	crudSnapshot   []byte
	lockProposal   LockProposal
}

type protoFragmentState struct {
	schemaID   SchemaID
	schemaKey  SchemaKey
	protoBytes []byte
	sourceRefs []provenance.SourceRef
}

type fragmentSchema struct {
	id         SchemaID
	key        SchemaKey
	sourceRefs []provenance.SourceRef
}

// BuildFragments projects one complete Proto file per CRUD-enabled Ent schema while
// retaining one aggregate compatibility reconciliation for the complete schema set.
func BuildFragments(entities entity.Document, spec FragmentSpec) (FragmentProjection, error) {
	entitySnapshot, err := entity.CanonicalJSON(entities)
	if err != nil {
		return FragmentProjection{}, buildError("document_state_invalid", "/entities")
	}

	schemas, err := fragmentSchemas(entities)
	if err != nil {
		return FragmentProjection{}, err
	}
	document, proposal, err := Build(entities, Spec{
		ServiceID:    spec.ServiceID,
		ProtoPackage: spec.ProtoPackage,
		GoPackage:    spec.GoPackage,
		ExistingLock: spec.ExistingLock,
		MultiTenant:  spec.MultiTenant,
	})
	if err != nil {
		return FragmentProjection{}, err
	}

	states := make([]*protoFragmentState, 0, len(schemas))
	for _, schema := range schemas {
		fragmentDocument, err := projectFragmentDocument(document, schema.id)
		if err != nil {
			return FragmentProjection{}, err
		}
		content, err := Render(fragmentDocument)
		if err != nil {
			return FragmentProjection{}, err
		}
		content = append([]byte(GeneratedProtoMarker+"\n"), content...)
		states = append(states, &protoFragmentState{
			schemaID: schema.id, schemaKey: schema.key,
			protoBytes: append([]byte(nil), content...),
			sourceRefs: append([]provenance.SourceRef(nil), schema.sourceRefs...),
		})
	}
	if err := compileFragmentSet(states); err != nil {
		return FragmentProjection{}, err
	}

	return FragmentProjection{state: &fragmentProjectionState{
		fragments: states, entitySnapshot: append([]byte(nil), entitySnapshot...),
		crudSnapshot: document.CanonicalJSON(), lockProposal: proposal,
	}}, nil
}

func (p FragmentProjection) Valid() bool { return p.state != nil }

func (p FragmentProjection) Fragments() []ProtoFragment {
	if p.state == nil {
		return nil
	}
	result := make([]ProtoFragment, len(p.state.fragments))
	for index, state := range p.state.fragments {
		result[index] = ProtoFragment{state: state}
	}
	return result
}

func (p FragmentProjection) EntitySnapshot() []byte {
	if p.state == nil {
		return nil
	}
	return append([]byte(nil), p.state.entitySnapshot...)
}

func (p FragmentProjection) CRUDSnapshot() []byte {
	if p.state == nil {
		return nil
	}
	return append([]byte(nil), p.state.crudSnapshot...)
}

func (p FragmentProjection) LockProposal() LockProposal {
	if p.state == nil {
		return LockProposal{}
	}
	return p.state.lockProposal
}

func (f ProtoFragment) Valid() bool { return f.state != nil }

func (f ProtoFragment) SchemaID() SchemaID {
	if f.state == nil {
		return ""
	}
	return f.state.schemaID
}

func (f ProtoFragment) SchemaKey() SchemaKey {
	if f.state == nil {
		return ""
	}
	return f.state.schemaKey
}

func (f ProtoFragment) ProtoBytes() []byte {
	if f.state == nil {
		return nil
	}
	return append([]byte(nil), f.state.protoBytes...)
}

func (f ProtoFragment) SourceRefs() []provenance.SourceRef {
	if f.state == nil {
		return nil
	}
	return append([]provenance.SourceRef(nil), f.state.sourceRefs...)
}

func fragmentSchemas(document entity.Document) ([]fragmentSchema, error) {
	result := make([]fragmentSchema, 0)
	keys := map[SchemaKey]SchemaID{}
	for index, item := range document.Entities() {
		if _, enabled := item.CRUD(); !enabled {
			continue
		}
		key, err := schemaKey(item.Name())
		if err != nil {
			if typed, ok := err.(*Error); ok && typed.Reason() == "schema_key_too_long" {
				return nil, buildError("schema_key_too_long", "/entities/"+itoa(index)+"/name")
			}
			return nil, buildError("schema_key_invalid", "/entities/"+itoa(index)+"/name")
		}
		schemaID := SchemaID(item.ID())
		if existing, collision := keys[key]; collision && existing != schemaID {
			return nil, buildError("schema_key_collision", "/entities/"+itoa(index)+"/name")
		}
		keys[key] = schemaID
		result = append(result, fragmentSchema{id: schemaID, key: key, sourceRefs: entitySourceRefs(item)})
	}
	sort.Slice(result, func(i, j int) bool { return string(result[i].key) < string(result[j].key) })
	return result, nil
}

func schemaKey(name string) (SchemaKey, error) {
	if name == "" {
		return "", errBuild
	}
	for index := 0; index < len(name); index++ {
		value := name[index]
		if value >= 0x80 || value != '_' && !asciiLetter(value) && !asciiDigit(value) {
			return "", errBuild
		}
	}

	tokens := make([]string, 0)
	for _, part := range strings.Split(name, "_") {
		if part == "" {
			continue
		}
		start := 0
		for index := 1; index < len(part); index++ {
			current, previous := part[index], part[index-1]
			boundary := asciiUpper(current) && (asciiLower(previous) || asciiDigit(previous))
			if !boundary && asciiUpper(current) && asciiUpper(previous) && index+1 < len(part) && asciiLower(part[index+1]) {
				boundary = true
			}
			if boundary {
				tokens = append(tokens, strings.ToLower(part[start:index]))
				start = index
			}
		}
		tokens = append(tokens, strings.ToLower(part[start:]))
	}
	if len(tokens) == 0 {
		return "", errBuild
	}
	for _, token := range tokens {
		if token == "" {
			return "", errBuild
		}
		for index := 0; index < len(token); index++ {
			if !asciiLower(token[index]) && !asciiDigit(token[index]) {
				return "", errBuild
			}
		}
	}
	key := SchemaKey(strings.Join(tokens, "-"))
	if len(key) > MaxSchemaKeyBytes {
		return "", buildError("schema_key_too_long", "/entities")
	}
	return key, nil
}

func projectFragmentDocument(document Document, schemaID SchemaID) (Document, error) {
	state := document.state
	fragment := &documentState{
		serviceID: state.serviceID, protoPackage: state.protoPackage, goPackage: state.goPackage,
		enums: []*enumState{}, messages: []*messageState{}, services: []*serviceState{}, sources: []provenance.Source{}, tenantEntityIDs: []string{},
	}
	prefix := string(schemaID) + "/"
	for _, value := range state.enums {
		if strings.HasPrefix(value.id, prefix) {
			fragment.enums = append(fragment.enums, value)
		}
	}
	for _, value := range state.messages {
		if strings.HasPrefix(value.id, prefix) {
			fragment.messages = append(fragment.messages, value)
		}
	}
	for _, value := range state.services {
		if strings.HasPrefix(value.id, prefix) {
			fragment.services = append(fragment.services, value)
		}
	}
	if containsName(state.tenantEntityIDs, string(schemaID)) {
		fragment.tenantEntityIDs = append(fragment.tenantEntityIDs, string(schemaID))
	}
	usedSources := map[string]struct{}{}
	for _, message := range fragment.messages {
		for _, field := range message.fields {
			usedSources[field.source.Ref.String()] = struct{}{}
		}
	}
	for _, source := range state.sources {
		if _, used := usedSources[source.Ref.String()]; used {
			fragment.sources = append(fragment.sources, source)
		}
	}
	fragment.imports = importsFor(fragment.messages)
	if servicesUseRPCContext(fragment.services) {
		fragment.imports = append(fragment.imports, "nexa/protocol/v1/options.proto")
		sort.Strings(fragment.imports)
	}
	return finalizeDocument(fragment)
}

func entitySourceRefs(item entity.Entity) []provenance.SourceRef {
	values := []provenance.Source{item.Source(), item.Identity().Source()}
	for _, field := range item.Fields() {
		values = append(values, field.Source())
	}
	for _, edge := range item.Edges() {
		values = append(values, edge.Source())
	}
	seen := map[string]provenance.SourceRef{}
	for _, source := range values {
		if source.Ref.String() != "" {
			seen[source.Ref.String()] = source.Ref
		}
	}
	result := make([]provenance.SourceRef, 0, len(seen))
	for _, ref := range seen {
		result = append(result, ref)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].String() < result[j].String() })
	return result
}

func compileFragmentSet(fragments []*protoFragmentState) error {
	if len(fragments) == 0 {
		return nil
	}
	files := map[string]string{"nexa/protocol/v1/options.proto": string(genprotocol.OptionsProto())}
	names := make([]string, len(fragments))
	for index, fragment := range fragments {
		name := fmt.Sprintf("__crudbuild_fragment_%03d.proto", index)
		names[index] = name
		files[name] = string(fragment.protoBytes)
	}
	resolver := &protocompile.SourceResolver{Accessor: protocompile.SourceAccessorFromMap(files)}
	compiler := protocompile.Compiler{Resolver: protocompile.WithStandardImports(resolver)}
	compiled, err := compiler.Compile(context.Background(), names...)
	if err != nil || len(compiled) != len(names) {
		return fragmentCompileError()
	}
	return nil
}

func fragmentCompileError() *Error {
	return &Error{code: "crud_proto_compile_failed", stage: "compile", reason: "proto_compile_failed", pointer: "/fragments", sentinel: errCompile}
}

func asciiLetter(value byte) bool { return asciiLower(value) || asciiUpper(value) }
func asciiLower(value byte) bool  { return value >= 'a' && value <= 'z' }
func asciiUpper(value byte) bool  { return value >= 'A' && value <= 'Z' }
func asciiDigit(value byte) bool  { return value >= '0' && value <= '9' }
