package composition

import (
	"io/fs"
	"path"
	"sort"

	"github.com/nxnminieye/nexa/generation/httpapi"
	"github.com/nxnminieye/nexa/provenance"
)

const artifactOwner = "nexa.dev/generator/composition/v1"

// Render emits only canonical .api source. RPC/domain adapters are explicit
// consumer code and are not described or generated by this compiler pass.
func Render(document Document, options RenderOptions) ([]RenderedArtifact, error) {
	if document.state == nil {
		return nil, invalid("document_invalid", "", "/document", "composition document is invalid")
	}
	if !fs.ValidPath(options.CoreRoot) || options.CoreRoot == "." {
		return nil, invalid("core_root_invalid", "", "/options/coreRoot", "Core root is invalid")
	}
	byService := map[string][]*operationState{}
	for _, operation := range document.state.operations {
		byService[operation.serviceID] = append(byService[operation.serviceID], operation)
	}
	serviceIDs := make([]string, 0, len(byService))
	for serviceID := range byService {
		serviceIDs = append(serviceIDs, serviceID)
	}
	sort.Strings(serviceIDs)
	artifacts := make([]RenderedArtifact, 0, len(serviceIDs))
	for _, serviceID := range serviceIDs {
		operations := byService[serviceID]
		var types []*projectedTypeState
		for _, value := range document.state.types {
			if value.serviceID == serviceID {
				types = append(types, value)
			}
		}
		partial := Document{state: &documentState{coreServiceID: document.state.coreServiceID, consumerModulePath: document.state.consumerModulePath, operations: operations, types: types}}
		generated, err := GeneratedAPI(partial)
		if err != nil {
			return nil, err
		}
		apiBytes, err := httpapi.RenderGenerated(generated)
		if err != nil {
			return nil, invalid("api_render_failed", "", "", err.Error())
		}
		apiFile := serviceID + ".generated.api"
		if serviceID == document.state.coreServiceID {
			apiFile = serviceID + ".proxy.generated.api"
		}
		artifacts = append(artifacts, artifact("api."+serviceID, path.Join(options.CoreRoot, "desc/generated", apiFile), apiBytes, unionSources(operationSources(operations), typeSources(types))))
	}
	return artifacts, nil
}

func artifact(id, artifactPath string, content []byte, sources []provenance.SourceRef) RenderedArtifact {
	return RenderedArtifact{ID: id, Path: artifactPath, Owner: artifactOwner, Content: append([]byte(nil), content...), Sources: append([]provenance.SourceRef(nil), sources...)}
}

func typeSources(types []*projectedTypeState) []provenance.SourceRef {
	set := map[string]provenance.SourceRef{}
	for _, projected := range types {
		for _, source := range projected.provenance.Sources() {
			set[source.Ref.String()] = source.Ref
		}
		for _, field := range projected.fields {
			for _, source := range field.provenance.Sources() {
				set[source.Ref.String()] = source.Ref
			}
		}
	}
	return sortedSourceSet(set)
}

func operationSources(operations []*operationState) []provenance.SourceRef {
	set := map[string]provenance.SourceRef{}
	for _, operation := range operations {
		for _, source := range operation.provenance.Sources() {
			set[source.Ref.String()] = source.Ref
		}
	}
	return sortedSourceSet(set)
}

func unionSources(values ...[]provenance.SourceRef) []provenance.SourceRef {
	set := map[string]provenance.SourceRef{}
	for _, refs := range values {
		for _, ref := range refs {
			set[ref.String()] = ref
		}
	}
	return sortedSourceSet(set)
}

func sortedSourceSet(set map[string]provenance.SourceRef) []provenance.SourceRef {
	result := make([]provenance.SourceRef, 0, len(set))
	for _, ref := range set {
		result = append(result, ref)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].String() < result[j].String() })
	return result
}
