package sdkpythonassets

import "fmt"

type LoaderMode string

const (
	SourceTreeMode     LoaderMode = "source-tree"
	InstalledWheelMode LoaderMode = "installed-wheel"
)

func generateBootstrap(c AssetBundleBootstrapContract) []byte {
	return []byte(fmt.Sprintf(`# Generated by Nexa's Python asset bundle writer. Do not edit.
import hashlib
import json
import os

INDEX_PATH = %q
BUNDLE_API_VERSION = %q
RAW_BYTES = %d
JSON_DEPTH = %d
JSON_NODES = %d
ROLE_RAW_BYTES = %d
ROLE_JSON_DEPTH = %d
ROLE_JSON_NODES = %d
ROLE_IDS = %s

class AssetError(Exception):
    def __init__(self, reason):
        self.reason = reason
        super().__init__(reason)

def _open_package_root(path):
    flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    try:
        fd = os.open(path, flags)
    except OSError:
        raise AssetError("package_root_invalid") from None
    try:
        st = os.fstat(fd)
        if (st.st_mode & 0o170000) != 0o040000:
            raise AssetError("package_root_invalid")
        return fd
    except BaseException:
        os.close(fd)
        raise

def _open_dir_at(parent, name, reason):
    if not isinstance(name, str) or not name or name in (".", "..") or "/" in name or "\\" in name:
        raise AssetError(reason)
    flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    try:
        return os.open(name, flags, dir_fd=parent)
    except OSError:
        raise AssetError(reason) from None

def _read_bounded_at(root, relative_path, raw_bytes, reason):
    parts = relative_path.split("/")
    if not parts or any(not part or part in (".", "..") or "\\" in part for part in parts):
        raise AssetError(reason)
    parent = os.dup(root)
    try:
        for part in parts[:-1]:
            child = _open_dir_at(parent, part, reason)
            os.close(parent)
            parent = child
        flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0) | getattr(os, "O_NONBLOCK", 0)
        try:
            fd = os.open(parts[-1], flags, dir_fd=parent)
        except OSError:
            raise AssetError(reason) from None
    finally:
        os.close(parent)
    try:
        st = os.fstat(fd)
        if (st.st_mode & 0o170000) != 0o100000 or st.st_size > raw_bytes:
            raise AssetError(reason)
        chunks, remaining = [], raw_bytes + 1
        while remaining:
            chunk = os.read(fd, remaining)
            if not chunk:
                break
            chunks.append(chunk)
            remaining -= len(chunk)
        data = b"".join(chunks)
        if len(data) > raw_bytes:
            raise AssetError(reason)
        return data
    except AssetError:
        raise
    except OSError:
        raise AssetError(reason) from None
    finally:
        os.close(fd)

def _pairs(rows, reason):
    result = {}
    for key, value in rows:
        if key in result:
            raise AssetError(reason)
        result[key] = value
    return result

def _bounds(value, depth, nodes, max_depth, max_nodes, reason):
    nodes[0] += 1
    if depth > max_depth or nodes[0] > max_nodes:
        raise AssetError(reason)
    if isinstance(value, dict):
        for child in value.values():
            _bounds(child, depth + 1, nodes, max_depth, max_nodes, reason)
    elif isinstance(value, list):
        for child in value:
            _bounds(child, depth + 1, nodes, max_depth, max_nodes, reason)

def _canonical(data, max_depth, max_nodes, reason):
    try:
        value = json.loads(data.decode("utf-8"), object_pairs_hook=lambda rows: _pairs(rows, reason))
        _bounds(value, 0, [0], max_depth, max_nodes, reason)
        encoded = json.dumps(value, ensure_ascii=False, allow_nan=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
        if encoded != data:
            raise AssetError(reason)
        return value
    except AssetError:
        raise
    except (UnicodeError, ValueError, TypeError):
        raise AssetError(reason) from None

def _digest(data):
    return "sha256:" + hashlib.sha256(data).hexdigest()

def _role_path(row, reason):
    if not isinstance(row, dict):
        raise AssetError(reason)
    digest = row.get("digest")
    if not isinstance(digest, str) or len(digest) != 71 or not digest.startswith("sha256:"):
        raise AssetError(reason)
    digest_hex = digest[7:]
    if any(ch not in "0123456789abcdef" for ch in digest_hex):
        raise AssetError(reason)
    expected = "objects/sha256/" + digest_hex + ".json"
    if row.get("path") != expected:
        raise AssetError(reason)
    return digest, expected

def _validate_index(index):
    if not isinstance(index, dict) or set(index) != {"apiVersion", "roles"} or index.get("apiVersion") != BUNDLE_API_VERSION:
        raise AssetError("bundle_index_drift")
    roles = index.get("roles")
    if not isinstance(roles, dict) or sorted(roles) != ROLE_IDS:
        raise AssetError("bundle_role_set_drift")
    for role_id, row in roles.items():
        if not isinstance(role_id, str) or not role_id or "/" in role_id:
            raise AssetError("bundle_role_set_drift")
        if not isinstance(row, dict) or not {"apiVersion", "mediaType", "path", "digest"}.issubset(row) or not set(row).issubset({"apiVersion", "mediaType", "path", "digest", "schemaRole"}):
            raise AssetError("bundle_role_drift")
        if not isinstance(row["apiVersion"], str) or not row["apiVersion"] or len(row["apiVersion"]) > 256:
            raise AssetError("bundle_role_drift")
        if row["mediaType"] not in ("application/json", "application/schema+json"):
            raise AssetError("bundle_role_drift")
        if "schemaRole" in row and (not isinstance(row["schemaRole"], str) or not row["schemaRole"] or len(row["schemaRole"]) > 256):
            raise AssetError("bundle_role_drift")
        _role_path(row, "bundle_role_drift")
    for row in roles.values():
        schema_role = row.get("schemaRole")
        if row["mediaType"] == "application/schema+json":
            if schema_role is not None:
                raise AssetError("bundle_role_drift")
        elif schema_role not in roles or roles[schema_role]["mediaType"] != "application/schema+json":
            raise AssetError("bundle_role_drift")

def _validate_index_schema(index, schema):
    if not isinstance(schema, dict):
        raise AssetError("bundle_index_schema_drift")
    try:
        if schema.get("type") != "object" or schema.get("additionalProperties") is not False:
            raise AssetError("bundle_index_schema_drift")
        roles_schema = schema["properties"]["roles"]
        required = roles_schema["required"]
        properties = roles_schema["properties"]
        role_def = schema["$defs"]["role"]
        if (schema.get("required") != ["apiVersion", "roles"] or
            not isinstance(required, list) or sorted(required) != sorted(index["roles"]) or
            not isinstance(properties, dict) or sorted(properties) != sorted(index["roles"]) or
            role_def.get("additionalProperties") is not False or
            sorted(role_def.get("required", [])) != ["apiVersion", "digest", "mediaType", "path"] or
            sorted(role_def.get("properties", {})) != ["apiVersion", "digest", "mediaType", "path", "schemaRole"]):
            raise AssetError("bundle_index_schema_drift")
    except (KeyError, TypeError):
        raise AssetError("bundle_index_schema_drift") from None

class AssetContext:
    def __init__(self, mode, package_root):
        self.mode = mode
        self.package_root = package_root
        self.root = None
        self.index = None
        self._entered = False

    def __enter__(self):
        if self._entered or self.mode not in ("source-tree", "installed-wheel"):
            raise AssetError("mode_invalid")
        self.root = _open_package_root(self.package_root)
        try:
            index_data = _read_bounded_at(self.root, INDEX_PATH, RAW_BYTES, "bundle_index_drift")
            self.index = _canonical(index_data, JSON_DEPTH, JSON_NODES, "bundle_index_drift")
            _validate_index(self.index)
            schema = self.read_role("bundle-index-schema", entering=True)
            _validate_index_schema(self.index, schema)
            self._entered = True
            return self
        except BaseException:
            self.close()
            raise

    def read_role(self, role_id, entering=False):
        if (not entering and not self._entered) or self.index is None:
            raise AssetError("context_invalid")
        roles = self.index.get("roles")
        row = roles.get(role_id) if isinstance(roles, dict) and isinstance(role_id, str) else None
        digest, relative = _role_path(row, "bundle_role_drift")
        data = _read_bounded_at(self.root, "_generated/" + relative, ROLE_RAW_BYTES, "bundle_role_drift")
        if _digest(data) != digest:
            raise AssetError("bundle_role_drift")
        return _canonical(data, ROLE_JSON_DEPTH, ROLE_JSON_NODES, "bundle_role_drift")

    def close(self):
        self._entered = False
        root, self.root = self.root, None
        if root is not None:
            os.close(root)

    def __exit__(self, exc_type, exc, traceback):
        self.close()
        return False

def open_asset_context(mode, package_root):
    return AssetContext(mode, package_root)

def load_asset_anchor(mode, package_root):
    with open_asset_context(mode, package_root) as assets:
        return assets.index
`, c.IndexPath, c.BundleAPIVersion, c.RawBytes, c.JSONDepth, c.JSONNodes, c.RoleRawBytes, c.RoleJSONDepth, c.RoleJSONNodes, pythonStringList(closedRoleIDs)))
}

func pythonStringList(values []string) string {
	result := "["
	for index, value := range values {
		if index > 0 {
			result += ", "
		}
		result += fmt.Sprintf("%q", value)
	}
	return result + "]"
}
