package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const helperVersion = "nexa-generation-helper v1.0.0"

type artifactWire struct {
	Digest string `json:"digest"`
	ID     string `json:"id"`
	Path   string `json:"path"`
	Role   string `json:"role"`
}

type rpcResult struct {
	APIVersion   string         `json:"apiVersion"`
	Artifacts    []artifactWire `json:"artifacts"`
	GoTestPassed bool           `json:"goTestPassed"`
	InputDigest  string         `json:"inputDigest"`
	Kind         string         `json:"kind"`
	ServiceID    string         `json:"serviceId"`
}

type apiResult struct {
	APIVersion    string         `json:"apiVersion"`
	Artifacts     []artifactWire `json:"artifacts"`
	CoreServiceID string         `json:"coreServiceId"`
	GoTestPassed  bool           `json:"goTestPassed"`
	InputDigest   string         `json:"inputDigest"`
	Kind          string         `json:"kind"`
}

func main() {
	if len(os.Args) == 2 && os.Args[1] == "version" {
		fmt.Println(helperVersion)
		return
	}
	if len(os.Args) != 5 || os.Args[2] != "generate" {
		panic("invalid helper arguments")
	}
	input, err := io.ReadAll(os.Stdin)
	if err != nil {
		panic(err)
	}
	root, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	var output []byte
	switch os.Args[1] {
	case "rpc":
		if os.Args[3] != "--service" {
			panic("invalid RPC arguments")
		}
		output = generateRPC(root, os.Args[4], input)
	case "api":
		if os.Args[3] != "--core-service" {
			panic("invalid API arguments")
		}
		output = generateAPI(root, os.Args[4], input)
	default:
		panic("unknown helper mode")
	}
	if _, err := os.Stdout.Write(output); err != nil {
		panic(err)
	}
}

func generateRPC(root, service string, input []byte) []byte {
	files := map[string][]byte{
		"backend/" + service + "/generated/" + service + ".proto":   []byte("syntax = \"proto3\";\npackage generated." + service + ".v1;\noption go_package = \"example.com/nexa-generation-consumer/backend/" + service + "/generated;generated\";\nmessage GeneratedContract {}\n"),
		"backend/" + service + "/internal/pb/" + service + ".pb.go": []byte("// Code generated by the consumer RPC helper. DO NOT EDIT.\npackage accountpb\n\ntype GeneratedAccount struct { ID string }\n"),
	}
	artifacts := make([]artifactWire, 0, len(files))
	for name, content := range files {
		write(root, name, content)
		artifacts = append(artifacts, artifactWire{Digest: digest(content), ID: "rpc." + strings.TrimPrefix(filepath.Ext(name), "."), Path: filepath.ToSlash(name), Role: "generated"})
	}
	sort.Slice(artifacts, func(i, j int) bool { return artifacts[i].ID < artifacts[j].ID })
	return marshal(rpcResult{APIVersion: "nexa.dev/rpc-go-result/v1", Artifacts: artifacts, GoTestPassed: true, InputDigest: digest(input), Kind: "RPCGoResult", ServiceID: service})
}

func generateAPI(root, core string, input []byte) []byte {
	artifacts := make([]artifactWire, 0)
	err := filepath.WalkDir(root, func(name string, entry os.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}
		extension := filepath.Ext(name)
		if extension != ".go" && extension != ".api" {
			return nil
		}
		relative, err := filepath.Rel(root, name)
		if err != nil {
			return err
		}
		relative = filepath.ToSlash(relative)
		content, err := os.ReadFile(name)
		if err != nil {
			return err
		}
		artifacts = append(artifacts, artifactWire{Digest: digest(content), ID: apiArtifactID(relative, core), Path: relative, Role: "generated"})
		return nil
	})
	if err != nil {
		panic(err)
	}
	sort.Slice(artifacts, func(i, j int) bool { return artifacts[i].ID < artifacts[j].ID })
	return marshal(apiResult{APIVersion: "nexa.dev/api-go-result/v1", Artifacts: artifacts, CoreServiceID: core, GoTestPassed: true, InputDigest: digest(input), Kind: "APIGoResult"})
}

func apiArtifactID(name, core string) string {
	switch {
	case name == "backend/"+core+"/desc/generated/"+core+".generated.api":
		return "api.aggregate." + core
	case strings.Contains(name, "/desc/generated/") && strings.HasSuffix(name, ".generated.api"):
		return "api." + strings.TrimSuffix(filepath.Base(name), ".generated.api")
	case strings.HasSuffix(name, "/client.generated.go"):
		return "client." + filepath.Base(filepath.Dir(name))
	case strings.HasSuffix(name, "/errors.generated.go"):
		return "errors." + filepath.Base(filepath.Dir(name))
	case strings.HasSuffix(name, "/mapper.generated.go"):
		return "mapper." + filepath.Base(filepath.Dir(name))
	case strings.Contains(name, "/internal/logic/rpcproxy/"):
		return "logic." + strings.ReplaceAll(strings.TrimSuffix(filepath.Base(name), ".generated.go"), "-", ".")
	case strings.HasSuffix(name, "/internal/rpcproxy/generated/register.generated.go"):
		return "register"
	default:
		panic("unrecognized staged API artifact: " + name)
	}
}

func write(root, name string, content []byte) {
	filename := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(filename), 0o700); err != nil {
		panic(err)
	}
	if err := os.WriteFile(filename, content, 0o600); err != nil {
		panic(err)
	}
}

func digest(content []byte) string {
	value := sha256.Sum256(content)
	return "sha256:" + hex.EncodeToString(value[:])
}

func marshal(value any) []byte {
	data, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return data
}
