ALTER TABLE roles
  ADD COLUMN default_router TEXT NOT NULL DEFAULT '/';

ALTER TABLE menus
  ADD COLUMN route_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN permission_code TEXT NOT NULL DEFAULT '',
  ADD COLUMN keep_alive BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN visible BOOLEAN NOT NULL DEFAULT TRUE;
