package crudlogic

import (
	"strings"
	"testing"

	"github.com/nxnminieye/nexa/generation/transaction"
	"github.com/nxnminieye/nexa/provenance"
)

func TestRenderTenantHelperUsesFrozenContract(t *testing.T) {
	got, err := renderTenantHelper()
	if err != nil {
		t.Fatalf("renderTenantHelper() error = %v", err)
	}
	for _, want := range []string{
		"package crudtenant",
		"func RequireTenantID(value int64) (int, error)",
		`codes.Unauthenticated, "tenant context is required"`,
	} {
		if !strings.Contains(string(got), want) {
			t.Fatalf("tenant helper missing %q:\n%s", want, got)
		}
	}
}

func TestGoIdentifierPreservesAcronymsAndSnakeCase(t *testing.T) {
	for input, want := range map[string]string{
		"acl_api_ascii_aws_cpu_css_dns_eof_gb_guid": "ACLAPIASCIIAWSCPUCSSDNSEOFGBGUID",
		"hcl_html_http_https_id_ip_json_kb_lhs_mac": "HCLHTMLHTTPHTTPSIDIPJSONKBLHSMAC",
		"mb_qps_ram_rhs_rpc_sla_smtp_sql_ssh_sso":   "MBQPSRAMRHSRPCSLASMTPSQLSSHSSO",
		"tcp_tls_ttl_udp_ui_uid_uri_url_utf8_uuid":  "TCPTLSTTLUDPUIUIDURIURLUTF8UUID",
		"vm_xml_xmpp_xsrf_xss":                      "VMXMLXMPPXSRFXSS",
		"display_name":                              "DisplayName",
	} {
		if got := exportedIdentifier(input); got != want {
			t.Errorf("exportedIdentifier(%q) = %q, want %q", input, got, want)
		}
	}
}

func TestGeneratedHelpersAreMethodScoped(t *testing.T) {
	if list, get := generatedHelperName("ListAccount", "toPB"), generatedHelperName("GetAccount", "toPB"); list != "listAccountToPB" || get != "getAccountToPB" || list == get {
		t.Fatalf("method-scoped helpers = %q %q", list, get)
	}
}

func TestTenantHelperOwnershipProbeSealsIdentityAndGeneratedShape(t *testing.T) {
	content, err := renderTenantHelper()
	if err != nil {
		t.Fatal(err)
	}
	id, artifactPath := tenantHelperIdentity(ServiceLayout{ServiceID: "account", LogicRoot: "backend/account/internal/logic"})
	probe := tenantHelperOwnershipProbe{id: id, path: artifactPath}
	expected := transaction.Ownership{GeneratorID: "crud-proto", ArtifactID: id, InputDigest: provenance.SHA256([]byte("input"))}
	owned, err := probe.Inspect(artifactPath, content, expected)
	if err != nil || !owned {
		t.Fatalf("generated helper owned = %v, error = %v", owned, err)
	}
	for name, test := range map[string]struct {
		path     string
		content  []byte
		expected transaction.Ownership
	}{
		"path":        {path: "backend/other/internal/logic/crudtenant/tenant.generated.go", content: content, expected: expected},
		"generator":   {path: artifactPath, content: content, expected: transaction.Ownership{GeneratorID: "crud-logic", ArtifactID: id, InputDigest: expected.InputDigest}},
		"artifact":    {path: artifactPath, content: content, expected: transaction.Ownership{GeneratorID: "crud-proto", ArtifactID: "other", InputDigest: expected.InputDigest}},
		"digest":      {path: artifactPath, content: content, expected: transaction.Ownership{GeneratorID: "crud-proto", ArtifactID: id}},
		"marker":      {path: artifactPath, content: []byte(strings.Replace(string(content), "// Code generated by Nexa. DO NOT EDIT.\n", "", 1)), expected: expected},
		"declaration": {path: artifactPath, content: []byte(strings.Replace(string(content), "RequireTenantID", "OtherTenantID", 1)), expected: expected},
	} {
		t.Run(name, func(t *testing.T) {
			owned, err := probe.Inspect(test.path, test.content, test.expected)
			if err != nil || owned {
				t.Fatalf("owned = %v, error = %v", owned, err)
			}
		})
	}
}

func TestValidatedPlanReturnsDefensiveTenantHelperStaleProbes(t *testing.T) {
	plan := ValidatedPlan{state: &validatedPlanState{plan: &planState{layout: ServiceLayout{ServiceID: "account", EntSchemaDir: "backend/account/ent/schema", LogicRoot: "backend/account/internal/logic"}}}}
	first, err := plan.StaleOwnershipProbes()
	if err != nil || len(first) != 1 || first[0] == nil {
		t.Fatalf("first probes = %#v, error = %v", first, err)
	}
	first[0] = nil
	second, err := plan.StaleOwnershipProbes()
	if err != nil || len(second) != 1 || second[0] == nil {
		t.Fatalf("second probes = %#v, error = %v", second, err)
	}
}
