package crudlogic

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/nxnminieye/nexa/generation/artifact"
	"github.com/nxnminieye/nexa/generation/transaction"
	"github.com/nxnminieye/nexa/provenance"
)

func TestStaleRPCOwnershipProbesDeleteUnmodifiedPB(t *testing.T) {
	repository := t.TempDir()
	protoPath := "backend/account/desc/account.crud.generated.proto"
	pbPath := "backend/account/internal/pb/account.crud.generated.pb.go"
	content := []byte("// Code generated by fixture. DO NOT EDIT.\n// source: " + protoPath + "\n\npackage accountpb\n")
	target := filepath.Join(repository, filepath.FromSlash(pbPath))
	if err := os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(target, content, 0o600); err != nil {
		t.Fatal(err)
	}
	sourceRef, err := provenance.RepositoryRef(protoPath, "protocol")
	if err != nil {
		t.Fatal(err)
	}
	sources := []provenance.Source{{Ref: sourceRef, Digest: provenance.SHA256([]byte("protocol"))}}
	previous, err := artifact.NewManifest(artifact.ManifestSpec{
		Generator: artifact.GeneratorSpec{ID: "crud-proto", Version: "v1.0.0"}, Sources: sources,
		Artifacts: []artifact.ArtifactSpec{{ID: "rpc.crud", Path: pbPath, Owner: "crud-proto", Digest: provenance.SHA256(content), Sources: []provenance.SourceRef{sourceRef}, StalePolicy: artifact.StaleDeleteIfUnmodified}},
	})
	if err != nil {
		t.Fatal(err)
	}
	manifestJSON, err := previous.CanonicalJSON()
	if err != nil {
		t.Fatal(err)
	}
	manifestPath := ".nexa/generation/crud-proto.account.manifest.json"
	manifestTarget := filepath.Join(repository, filepath.FromSlash(manifestPath))
	if err := os.MkdirAll(filepath.Dir(manifestTarget), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(manifestTarget, manifestJSON, 0o600); err != nil {
		t.Fatal(err)
	}
	probes := StaleRPCOwnershipProbes(&previous, ServiceLayout{ServiceID: "account", LogicRoot: "backend/account/internal/logic"}, protoPath, "accountpb")
	if len(probes) != 1 {
		t.Fatalf("stale probes = %d", len(probes))
	}
	plan, err := transaction.Build(context.Background(), repository, func(string, func(string, []byte) error) (transaction.PlanRequest, error) {
		return transaction.PlanRequest{Generator: artifact.GeneratorSpec{ID: "crud-proto", Version: "v1.0.0"}, Sources: sources, Previous: &previous, ManifestPath: manifestPath, StaleOwnershipProbes: probes, RevalidateSources: func(context.Context) ([]provenance.Source, error) { return sources, nil }}, nil
	})
	if err != nil {
		t.Fatal(err)
	}
	defer plan.Close()
	if len(plan.Conflicts()) != 0 || len(plan.Changes()) != 1 || plan.Changes()[0].Kind() != transaction.ChangeDelete || plan.Changes()[0].Path() != pbPath {
		t.Fatalf("changes = %#v conflicts = %#v", plan.Changes(), plan.Conflicts())
	}
	next, ok := plan.NextManifest()
	if !ok || len(next.Artifacts()) != 0 {
		t.Fatalf("next manifest artifacts = %#v, available = %v", next.Artifacts(), ok)
	}
	if _, err := transaction.Write(context.Background(), plan, repository, transaction.WriteOptions{PlanDigest: plan.PlanDigest()}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(target); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("stale PB still exists: %v", err)
	}
}
