package crudlogic

import (
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"path"
	"strings"

	"github.com/nxnminieye/nexa/generation/artifact"
	"github.com/nxnminieye/nexa/generation/transaction"
	"github.com/nxnminieye/nexa/provenance"
)

type tenantHelperOwnershipProbe struct{ id, path string }

type unifiedRPCOwnershipProbe struct {
	id, path, protoPath, packageName string
}

// StaleRPCOwnershipProbes restores the exact ownership checks needed to
// remove unmodified RPC artifacts after CRUD output is no longer required.
func StaleRPCOwnershipProbes(previous *artifact.Manifest, layout ServiceLayout, protoPath, packageName string) []transaction.OwnershipProbe {
	if previous == nil || previous.Generator().ID() != transactionGeneratorID || previous.Generator().Version() != "v1.0.0" {
		return nil
	}
	pbRoot := path.Join(path.Dir(layout.LogicRoot), "pb") + "/"
	result := make([]transaction.OwnershipProbe, 0)
	for _, item := range previous.Artifacts() {
		if item.StalePolicy() != artifact.StaleDeleteIfUnmodified || !strings.HasPrefix(item.ID(), "rpc.") || !strings.HasPrefix(item.Path(), pbRoot) || path.Ext(item.Path()) != ".go" {
			continue
		}
		result = append(result, unifiedRPCOwnershipProbe{id: item.ID(), path: item.Path(), protoPath: protoPath, packageName: packageName})
	}
	return result
}

func (p unifiedRPCOwnershipProbe) Inspect(name string, content []byte, expected transaction.Ownership) (bool, error) {
	if name != p.path || expected.GeneratorID != transactionGeneratorID || expected.ArtifactID != p.id {
		return false, nil
	}
	if _, err := provenance.ParseDigest(expected.InputDigest.String()); err != nil {
		return false, nil
	}
	file, err := parser.ParseFile(token.NewFileSet(), name, content, parser.ParseComments|parser.AllErrors)
	return err == nil && ast.IsGenerated(file) && file.Name.Name == p.packageName && generatedRPCProtoSourceAllowed(file, p.protoPath), nil
}

func tenantHelperIdentity(layout ServiceLayout) (string, string) {
	return artifactIDPrefix + "." + layout.ServiceID + ".tenant-helper", path.Join(layout.LogicRoot, "crudtenant/tenant.generated.go")
}

func (p tenantHelperOwnershipProbe) Inspect(name string, content []byte, expected transaction.Ownership) (bool, error) {
	if name != p.path || expected.GeneratorID != transactionGeneratorID || expected.ArtifactID != p.id {
		return false, nil
	}
	if _, err := provenance.ParseDigest(expected.InputDigest.String()); err != nil {
		return false, nil
	}
	file, err := parser.ParseFile(token.NewFileSet(), name, content, parser.ParseComments|parser.AllErrors)
	if err != nil || !ast.IsGenerated(file) || file.Name.Name != "crudtenant" {
		return false, nil
	}
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if ok && validTenantHelperDeclaration(function) {
			return true, nil
		}
	}
	return false, nil
}

func validTenantHelperDeclaration(function *ast.FuncDecl) bool {
	if function.Recv != nil || function.Name.Name != "RequireTenantID" || function.Type.Params == nil || function.Type.Results == nil || len(function.Type.Params.List) != 1 || len(function.Type.Results.List) != 2 {
		return false
	}
	parameter := function.Type.Params.List[0]
	return len(parameter.Names) == 1 && parameter.Names[0].Name == "value" && identifierName(parameter.Type) == "int64" && identifierName(function.Type.Results.List[0].Type) == "int" && identifierName(function.Type.Results.List[1].Type) == "error"
}

func identifierName(expression ast.Expr) string {
	if value, ok := expression.(*ast.Ident); ok {
		return value.Name
	}
	return ""
}

func renderTenantHelper() ([]byte, error) {
	return format.Source([]byte(`// Code generated by Nexa. DO NOT EDIT.
package crudtenant

import (
	"math"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func RequireTenantID(value int64) (int, error) {
	if value <= 0 || uint64(value) > uint64(math.MaxInt) {
		return 0, status.Error(codes.Unauthenticated, "tenant context is required")
	}
	return int(value), nil
}
`))
}
